"""
Расширенная база данных продуктов с точными значениями КБЖУ на 100г
Данные взяты из официальных источников:
USDA, calorizator.ru, Роспотребнадзор
"""

from typing import Dict, Optional, List


class NutritionDatabase:
    """База данных продуктов с точным КБЖУ"""

    # Формат: "название": {"calories": ккал, "protein": г,
    #                       "fat": г, "carbs": г, "category": категория}
    PRODUCTS = {
        # ==== БЕЛКОВЫЕ ПРОДУКТЫ ====
        # Мясо и птица
        "яйца куриные": {
            "calories": 157,
            "protein": 12.7,
            "fat": 11.5,
            "carbs": 0.7,
            "category": "protein",
        },
        "яйца": {
            "calories": 157,
            "protein": 12.7,
            "fat": 11.5,
            "carbs": 0.7,
            "category": "protein",
        },
        "курица грудка": {
            "calories": 113,
            "protein": 23.6,
            "fat": 1.9,
            "carbs": 0.4,
            "category": "protein",
        },
        "курица бедро": {
            "calories": 185,
            "protein": 16.8,
            "fat": 13.0,
            "carbs": 0.0,
            "category": "protein",
        },
        "курица филе": {
            "calories": 113,
            "protein": 23.6,
            "fat": 1.9,
            "carbs": 0.4,
            "category": "protein",
        },
        "курица": {
            "calories": 170,
            "protein": 20.0,
            "fat": 10.0,
            "carbs": 0.0,
            "category": "protein",
        },
        "индейка": {
            "calories": 115,
            "protein": 21.6,
            "fat": 2.8,
            "carbs": 0.0,
            "category": "protein",
        },
        "утка": {
            "calories": 405,
            "protein": 15.8,
            "fat": 38.0,
            "carbs": 0.0,
            "category": "protein",
        },
        "говядина": {
            "calories": 187,
            "protein": 18.9,
            "fat": 12.4,
            "carbs": 0.0,
            "category": "protein",
        },
        "телятина": {
            "calories": 97,
            "protein": 19.7,
            "fat": 2.0,
            "carbs": 0.0,
            "category": "protein",
        },
        "свинина постная": {
            "calories": 242,
            "protein": 16.0,
            "fat": 21.6,
            "carbs": 0.0,
            "category": "protein",
        },
        "свинина": {
            "calories": 259,
            "protein": 16.0,
            "fat": 21.6,
            "carbs": 0.0,
            "category": "protein",
        },
        "баранина": {
            "calories": 209,
            "protein": 16.3,
            "fat": 15.3,
            "carbs": 0.0,
            "category": "protein",
        },
        "кролик": {
            "calories": 156,
            "protein": 21.2,
            "fat": 8.0,
            "carbs": 0.0,
            "category": "protein",
        },
        "колбаса вареная": {
            "calories": 257,
            "protein": 12.0,
            "fat": 22.0,
            "carbs": 1.5,
            "category": "protein",
        },
        "колбаса копченая": {
            "calories": 380,
            "protein": 16.0,
            "fat": 34.0,
            "carbs": 2.0,
            "category": "protein",
        },
        "сосиски": {
            "calories": 266,
            "protein": 11.0,
            "fat": 24.0,
            "carbs": 1.5,
            "category": "protein",
        },
        # Расширенная база колбасных изделий с calorizator.ru
        "колбаса вареная диетическая": {
            "calories": 170.0,
            "protein": 12.1,
            "fat": 13.5,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса вареная докторская": {
            "calories": 257.0,
            "protein": 12.8,
            "fat": 22.2,
            "carbs": 1.5,
            "category": "sausages",
        },
        "колбаса докторская": {
            "calories": 257.0,
            "protein": 12.8,
            "fat": 22.2,
            "carbs": 1.5,
            "category": "sausages",
        },
        "докторская": {
            "calories": 257.0,
            "protein": 12.8,
            "fat": 22.2,
            "carbs": 1.5,
            "category": "sausages",
        },
        "колбаса вареная куриная": {
            "calories": 223.0,
            "protein": 15.5,
            "fat": 16.2,
            "carbs": 2.3,
            "category": "sausages",
        },
        "колбаса вареная любительская": {
            "calories": 301.0,
            "protein": 12.2,
            "fat": 28.0,
            "carbs": 0.1,
            "category": "sausages",
        },
        "колбаса вареная молочная": {
            "calories": 252.0,
            "protein": 11.7,
            "fat": 22.8,
            "carbs": 0.2,
            "category": "sausages",
        },
        "колбаса молочная": {
            "calories": 252.0,
            "protein": 11.7,
            "fat": 22.8,
            "carbs": 0.2,
            "category": "sausages",
        },
        "колбаса вареная московская": {
            "calories": 250.0,
            "protein": 11.5,
            "fat": 21.8,
            "carbs": 2.0,
            "category": "sausages",
        },
        "колбаса вареная русская": {
            "calories": 302.0,
            "protein": 11.8,
            "fat": 28.9,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса вареная свиная": {
            "calories": 277.0,
            "protein": 10.8,
            "fat": 25.8,
            "carbs": 0.5,
            "category": "sausages",
        },
        "колбаса вареная столичная": {
            "calories": 319.0,
            "protein": 15.1,
            "fat": 28.7,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса варено-копченая любительская": {
            "calories": 420.0,
            "protein": 17.2,
            "fat": 39.0,
            "carbs": 0.2,
            "category": "sausages",
        },
        "колбаса варено-копченая московская": {
            "calories": 406.0,
            "protein": 19.1,
            "fat": 36.6,
            "carbs": 0.2,
            "category": "sausages",
        },
        "колбаса варено-копченая сервелат": {
            "calories": 425.0,
            "protein": 16.1,
            "fat": 40.1,
            "carbs": 0.0,
            "category": "sausages",
        },
        "сервелат": {
            "calories": 425.0,
            "protein": 16.1,
            "fat": 40.1,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса ливерная": {
            "calories": 326.0,
            "protein": 14.4,
            "fat": 28.5,
            "carbs": 2.2,
            "category": "sausages",
        },
        "ливерная колбаса": {
            "calories": 326.0,
            "protein": 14.4,
            "fat": 28.5,
            "carbs": 2.2,
            "category": "sausages",
        },
        "колбаса печеночная": {
            "calories": 258.0,
            "protein": 15.0,
            "fat": 22.0,
            "carbs": 0.0,
            "category": "sausages",
        },
        "печеночная колбаса": {
            "calories": 258.0,
            "protein": 15.0,
            "fat": 22.0,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса полукопченая": {
            "calories": 376.0,
            "protein": 16.5,
            "fat": 34.4,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса полукопченая краковская": {
            "calories": 466.0,
            "protein": 16.2,
            "fat": 44.6,
            "carbs": 0.0,
            "category": "sausages",
        },
        "краковская": {
            "calories": 466.0,
            "protein": 16.2,
            "fat": 44.6,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса сыровяленая суджук": {
            "calories": 463.0,
            "protein": 30.3,
            "fat": 37.9,
            "carbs": 0.0,
            "category": "sausages",
        },
        "суджук": {
            "calories": 463.0,
            "protein": 30.3,
            "fat": 37.9,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса сыровяленая чоризо": {
            "calories": 455.0,
            "protein": 24.1,
            "fat": 38.3,
            "carbs": 1.9,
            "category": "sausages",
        },
        "чоризо": {
            "calories": 455.0,
            "protein": 24.1,
            "fat": 38.3,
            "carbs": 1.9,
            "category": "sausages",
        },
        "колбаса сырокопченая": {
            "calories": 473.0,
            "protein": 24.8,
            "fat": 41.5,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса сырокопченая московская": {
            "calories": 473.0,
            "protein": 24.8,
            "fat": 41.5,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса сырокопченая любительская": {
            "calories": 514.0,
            "protein": 20.9,
            "fat": 47.8,
            "carbs": 0.0,
            "category": "sausages",
        },
        "колбаса сырокопченая сервелат": {
            "calories": 461.0,
            "protein": 24.0,
            "fat": 40.5,
            "carbs": 0.0,
            "category": "sausages",
        },
        "салями": {
            "calories": 568.0,
            "protein": 21.6,
            "fat": 53.7,
            "carbs": 1.4,
            "category": "sausages",
        },
        "сардельки": {
            "calories": 215.0,
            "protein": 11.4,
            "fat": 18.2,
            "carbs": 1.5,
            "category": "sausages",
        },
        "сардельки говяжьи": {
            "calories": 215.0,
            "protein": 11.4,
            "fat": 18.2,
            "carbs": 1.5,
            "category": "sausages",
        },
        "сардельки свиные": {
            "calories": 332.0,
            "protein": 10.1,
            "fat": 31.6,
            "carbs": 1.9,
            "category": "sausages",
        },
        "сосиски говяжьи": {
            "calories": 226.0,
            "protein": 10.4,
            "fat": 20.1,
            "carbs": 0.8,
            "category": "sausages",
        },
        "сосиски куриные": {
            "calories": 259.0,
            "protein": 10.8,
            "fat": 22.4,
            "carbs": 4.2,
            "category": "sausages",
        },
        "сосиски молочные": {
            "calories": 266.0,
            "protein": 11.0,
            "fat": 23.9,
            "carbs": 1.6,
            "category": "sausages",
        },
        "шпикачки": {
            "calories": 337.0,
            "protein": 10.0,
            "fat": 33.0,
            "carbs": 0.0,
            "category": "sausages",
        },
        # Молочные продукты
        "рыба белая": {
            "calories": 90,
            "protein": 18.0,
            "fat": 2.0,
            "carbs": 0.0,
            "category": "protein",
        },
        "лосось": {
            "calories": 142,
            "protein": 19.8,
            "fat": 6.3,
            "carbs": 0.0,
            "category": "protein",
        },
        "семга": {
            "calories": 142,
            "protein": 19.8,
            "fat": 6.3,
            "carbs": 0.0,
            "category": "protein",
        },
        "форель": {
            "calories": 119,
            "protein": 19.2,
            "fat": 4.3,
            "carbs": 0.0,
            "category": "protein",
        },
        "тунец": {
            "calories": 101,
            "protein": 23.0,
            "fat": 1.3,
            "carbs": 0.0,
            "category": "protein",
        },
        "треска": {
            "calories": 69,
            "protein": 16.0,
            "fat": 0.6,
            "carbs": 0.0,
            "category": "protein",
        },
        "минтай": {
            "calories": 72,
            "protein": 15.9,
            "fat": 0.9,
            "carbs": 0.0,
            "category": "protein",
        },
        "хек": {
            "calories": 86,
            "protein": 16.6,
            "fat": 2.2,
            "carbs": 0.0,
            "category": "protein",
        },
        "скумбрия": {
            "calories": 191,
            "protein": 18.0,
            "fat": 13.2,
            "carbs": 0.0,
            "category": "protein",
        },
        "сельдь": {
            "calories": 161,
            "protein": 17.7,
            "fat": 10.0,
            "carbs": 0.0,
            "category": "protein",
        },
        "креветки": {
            "calories": 87,
            "protein": 20.0,
            "fat": 1.0,
            "carbs": 0.0,
            "category": "protein",
        },
        "кальмары": {
            "calories": 75,
            "protein": 18.0,
            "fat": 0.3,
            "carbs": 0.0,
            "category": "protein",
        },
        "мидии": {
            "calories": 77,
            "protein": 11.5,
            "fat": 2.0,
            "carbs": 3.3,
            "category": "protein",
        },
        "икра красная": {
            "calories": 249,
            "protein": 31.6,
            "fat": 13.2,
            "carbs": 1.0,
            "category": "protein",
        },
        # Рыба и морепродукты
        "творог 2%": {
            "calories": 101,
            "protein": 18.0,
            "fat": 2.0,
            "carbs": 3.3,
            "category": "dairy",
        },
        "творог 5%": {
            "calories": 121,
            "protein": 16.7,
            "fat": 5.0,
            "carbs": 1.8,
            "category": "dairy",
        },
        "творог 9%": {
            "calories": 159,
            "protein": 16.0,
            "fat": 9.0,
            "carbs": 2.0,
            "category": "dairy",
        },
        "творог": {
            "calories": 121,
            "protein": 16.7,
            "fat": 5.0,
            "carbs": 1.8,
            "category": "dairy",
        },
        "молоко 1.5%": {
            "calories": 44,
            "protein": 2.9,
            "fat": 1.5,
            "carbs": 4.8,
            "category": "dairy",
        },
        "молоко 2.5%": {
            "calories": 52,
            "protein": 2.8,
            "fat": 2.5,
            "carbs": 4.7,
            "category": "dairy",
        },
        "молоко 3.2%": {
            "calories": 60,
            "protein": 2.8,
            "fat": 3.2,
            "carbs": 4.7,
            "category": "dairy",
        },
        "молоко": {
            "calories": 52,
            "protein": 2.8,
            "fat": 2.5,
            "carbs": 4.7,
            "category": "dairy",
        },
        "кефир 1%": {
            "calories": 37,
            "protein": 3.0,
            "fat": 1.0,
            "carbs": 4.0,
            "category": "dairy",
        },
        "кефир 2.5%": {
            "calories": 50,
            "protein": 2.8,
            "fat": 2.5,
            "carbs": 3.9,
            "category": "dairy",
        },
        "кефир 3.2%": {
            "calories": 56,
            "protein": 2.9,
            "fat": 3.2,
            "carbs": 4.0,
            "category": "dairy",
        },
        "кефир": {
            "calories": 50,
            "protein": 2.8,
            "fat": 2.5,
            "carbs": 3.9,
            "category": "dairy",
        },
        "йогурт натуральный": {
            "calories": 60,
            "protein": 3.2,
            "fat": 3.2,
            "carbs": 3.5,
            "category": "dairy",
        },
        "йогурт греческий": {
            "calories": 73,
            "protein": 10.0,
            "fat": 1.8,
            "carbs": 4.0,
            "category": "dairy",
        },
        "сметана 10%": {
            "calories": 115,
            "protein": 3.0,
            "fat": 10.0,
            "carbs": 2.9,
            "category": "dairy",
        },
        "сметана 15%": {
            "calories": 158,
            "protein": 2.6,
            "fat": 15.0,
            "carbs": 3.0,
            "category": "dairy",
        },
        "сметана 20%": {
            "calories": 206,
            "protein": 2.8,
            "fat": 20.0,
            "carbs": 3.2,
            "category": "dairy",
        },
        "сметана": {
            "calories": 158,
            "protein": 2.6,
            "fat": 15.0,
            "carbs": 3.0,
            "category": "dairy",
        },
        "сливки 10%": {
            "calories": 118,
            "protein": 3.0,
            "fat": 10.0,
            "carbs": 4.0,
            "category": "dairy",
        },
        "сливки 20%": {
            "calories": 205,
            "protein": 2.8,
            "fat": 20.0,
            "carbs": 3.7,
            "category": "dairy",
        },
        "сыр твердый": {
            "calories": 360,
            "protein": 26.0,
            "fat": 27.0,
            "carbs": 0.0,
            "category": "dairy",
        },
        "сыр": {
            "calories": 360,
            "protein": 26.0,
            "fat": 27.0,
            "carbs": 0.0,
            "category": "dairy",
        },
        "сыр российский": {
            "calories": 364,
            "protein": 23.0,
            "fat": 30.0,
            "carbs": 0.0,
            "category": "dairy",
        },
        "сыр пармезан": {
            "calories": 392,
            "protein": 33.0,
            "fat": 28.0,
            "carbs": 0.0,
            "category": "dairy",
        },
        "моцарелла": {
            "calories": 280,
            "protein": 18.0,
            "fat": 22.0,
            "carbs": 2.2,
            "category": "dairy",
        },
        "сулугуни": {
            "calories": 290,
            "protein": 20.0,
            "fat": 24.0,
            "carbs": 0.0,
            "category": "dairy",
        },
        "фета": {
            "calories": 264,
            "protein": 14.2,
            "fat": 21.3,
            "carbs": 4.1,
            "category": "dairy",
        },
        "сыр плавленый": {
            "calories": 257,
            "protein": 16.8,
            "fat": 11.2,
            "carbs": 23.8,
            "category": "dairy",
        },
        # ==== УГЛЕВОДЫ ====
        # Крупы и злаки (в вареном виде)
        "рис белый": {
            "calories": 130,
            "protein": 2.7,
            "fat": 0.3,
            "carbs": 28.2,
            "category": "carbs",
        },
        "рис": {
            "calories": 130,
            "protein": 2.7,
            "fat": 0.3,
            "carbs": 28.2,
            "category": "carbs",
        },
        "рис бурый": {
            "calories": 111,
            "protein": 2.6,
            "fat": 0.9,
            "carbs": 23.0,
            "category": "carbs",
        },
        "гречка": {
            "calories": 123,
            "protein": 4.2,
            "fat": 1.1,
            "carbs": 25.0,
            "category": "carbs",
        },
        "овсянка": {
            "calories": 68,
            "protein": 2.4,
            "fat": 1.4,
            "carbs": 12.0,
            "category": "carbs",
        },
        "овсяная каша": {
            "calories": 68,
            "protein": 2.4,
            "fat": 1.4,
            "carbs": 12.0,
            "category": "carbs",
        },
        "перловка": {
            "calories": 109,
            "protein": 3.1,
            "fat": 0.4,
            "carbs": 22.2,
            "category": "carbs",
        },
        "пшено": {
            "calories": 119,
            "protein": 3.5,
            "fat": 1.0,
            "carbs": 23.0,
            "category": "carbs",
        },
        "кукурузная каша": {
            "calories": 96,
            "protein": 2.3,
            "fat": 0.5,
            "carbs": 20.7,
            "category": "carbs",
        },
        "макароны": {
            "calories": 112,
            "protein": 3.5,
            "fat": 0.4,
            "carbs": 23.2,
            "category": "carbs",
        },
        "лапша": {
            "calories": 112,
            "protein": 3.5,
            "fat": 0.4,
            "carbs": 23.2,
            "category": "carbs",
        },
        "спагетти": {
            "calories": 112,
            "protein": 3.5,
            "fat": 0.4,
            "carbs": 23.2,
            "category": "carbs",
        },
        "кускус": {
            "calories": 112,
            "protein": 3.8,
            "fat": 0.2,
            "carbs": 23.2,
            "category": "carbs",
        },
        "булгур": {
            "calories": 83,
            "protein": 3.1,
            "fat": 0.2,
            "carbs": 18.6,
            "category": "carbs",
        },
        # Расширенная база круп, каш и злаков с calorizator.ru
        "амарант": {
            "calories": 371,
            "protein": 13.6,
            "fat": 7.0,
            "carbs": 69.0,
            "category": "carbs",
        },
        "булгур приготовленный": {
            "calories": 83,
            "protein": 3.1,
            "fat": 0.2,
            "carbs": 14.1,
            "category": "carbs",
        },
        "горох колотый": {
            "calories": 299,
            "protein": 23.0,
            "fat": 1.5,
            "carbs": 48.1,
            "category": "carbs",
        },
        "горох маш": {
            "calories": 312,
            "protein": 23.5,
            "fat": 2.0,
            "carbs": 50.0,
            "category": "carbs",
        },
        "гречка зелёная вареная": {
            "calories": 110,
            "protein": 4.0,
            "fat": 1.0,
            "carbs": 21.0,
            "category": "carbs",
        },
        "гречка зелёная": {
            "calories": 295,
            "protein": 10.8,
            "fat": 3.2,
            "carbs": 54.4,
            "category": "carbs",
        },
        "гречневая каша вязкая": {
            "calories": 90,
            "protein": 3.2,
            "fat": 0.8,
            "carbs": 17.1,
            "category": "carbs",
        },
        "гречневая каша на молоке": {
            "calories": 118,
            "protein": 4.2,
            "fat": 2.3,
            "carbs": 21.6,
            "category": "carbs",
        },
        "гречневая каша с маслом": {
            "calories": 132,
            "protein": 4.5,
            "fat": 2.3,
            "carbs": 25.0,
            "category": "carbs",
        },
        "гречневая крупа продел": {
            "calories": 306,
            "protein": 9.5,
            "fat": 2.3,
            "carbs": 65.9,
            "category": "carbs",
        },
        "гречневая крупа ядрица": {
            "calories": 313,
            "protein": 12.6,
            "fat": 3.3,
            "carbs": 62.1,
            "category": "carbs",
        },
        "гречневая манка": {
            "calories": 350,
            "protein": 12.5,
            "fat": 2.5,
            "carbs": 70.0,
            "category": "carbs",
        },
        "гречневые хлопья": {
            "calories": 330,
            "protein": 9.0,
            "fat": 2.4,
            "carbs": 67.0,
            "category": "carbs",
        },
        "киноа": {
            "calories": 368,
            "protein": 14.1,
            "fat": 6.1,
            "carbs": 57.2,
            "category": "carbs",
        },
        "кукурузная крупа": {
            "calories": 337,
            "protein": 8.3,
            "fat": 1.2,
            "carbs": 75.0,
            "category": "carbs",
        },
        "кукурузная манка": {
            "calories": 340,
            "protein": 8.0,
            "fat": 1.0,
            "carbs": 75.0,
            "category": "carbs",
        },
        "кукурузные хлопья": {
            "calories": 363,
            "protein": 6.9,
            "fat": 2.5,
            "carbs": 83.6,
            "category": "carbs",
        },
        "кускус приготовленный": {
            "calories": 112,
            "protein": 3.8,
            "fat": 0.2,
            "carbs": 21.8,
            "category": "carbs",
        },
        "кускус сухой": {
            "calories": 376,
            "protein": 12.8,
            "fat": 0.6,
            "carbs": 72.4,
            "category": "carbs",
        },
        "льняная каша": {
            "calories": 312,
            "protein": 34.0,
            "fat": 14.0,
            "carbs": 12.0,
            "category": "carbs",
        },
        "льняные отруби": {
            "calories": 250,
            "protein": 30.0,
            "fat": 10.0,
            "carbs": 10.0,
            "category": "carbs",
        },
        "манная каша на воде": {
            "calories": 80,
            "protein": 2.5,
            "fat": 0.2,
            "carbs": 16.8,
            "category": "carbs",
        },
        "манная каша на молоке": {
            "calories": 98,
            "protein": 3.0,
            "fat": 3.2,
            "carbs": 15.3,
            "category": "carbs",
        },
        "манная крупа": {
            "calories": 328,
            "protein": 10.3,
            "fat": 1.0,
            "carbs": 67.4,
            "category": "carbs",
        },
        "манка": {
            "calories": 328,
            "protein": 10.3,
            "fat": 1.0,
            "carbs": 67.4,
            "category": "carbs",
        },
        "мюсли": {
            "calories": 363,
            "protein": 11.4,
            "fat": 7.8,
            "carbs": 56.7,
            "category": "carbs",
        },
        "мюсли фруктовые": {
            "calories": 333,
            "protein": 8.8,
            "fat": 5.1,
            "carbs": 62.6,
            "category": "carbs",
        },
        "мюсли шоколадные": {
            "calories": 400,
            "protein": 10.0,
            "fat": 13.0,
            "carbs": 62.0,
            "category": "carbs",
        },
        "нут сухой": {
            "calories": 385,
            "protein": 18.2,
            "fat": 9.4,
            "carbs": 62.6,
            "category": "carbs",
        },
        "овсяная крупа": {
            "calories": 342,
            "protein": 12.3,
            "fat": 6.1,
            "carbs": 59.5,
            "category": "carbs",
        },
        "овсяная манка": {
            "calories": 342,
            "protein": 12.3,
            "fat": 6.1,
            "carbs": 59.5,
            "category": "carbs",
        },
        "овсяные волокна": {
            "calories": 8,
            "protein": 0.8,
            "fat": 0.1,
            "carbs": 90.4,
            "category": "carbs",
        },
        "овсяные отруби": {
            "calories": 320,
            "protein": 18.0,
            "fat": 7.7,
            "carbs": 45.3,
            "category": "carbs",
        },
        "овсяные хлопья": {
            "calories": 366,
            "protein": 11.9,
            "fat": 7.2,
            "carbs": 69.3,
            "category": "carbs",
        },
        "овсяные хлопья геркулес": {
            "calories": 352,
            "protein": 12.5,
            "fat": 6.2,
            "carbs": 61.0,
            "category": "carbs",
        },
        "отруби пшеничные": {
            "calories": 180,
            "protein": 14.7,
            "fat": 4.1,
            "carbs": 20.6,
            "category": "carbs",
        },
        "отруби ржаные": {
            "calories": 221,
            "protein": 11.2,
            "fat": 3.2,
            "carbs": 32.0,
            "category": "carbs",
        },
        "перловая каша на воде": {
            "calories": 109,
            "protein": 3.1,
            "fat": 0.4,
            "carbs": 22.2,
            "category": "carbs",
        },
        "перловая крупа": {
            "calories": 320,
            "protein": 9.3,
            "fat": 1.1,
            "carbs": 73.7,
            "category": "carbs",
        },
        "полба": {
            "calories": 337,
            "protein": 14.7,
            "fat": 2.2,
            "carbs": 61.2,
            "category": "carbs",
        },
        "полбяная каша": {
            "calories": 127,
            "protein": 5.5,
            "fat": 0.9,
            "carbs": 26.5,
            "category": "carbs",
        },
        "пшеница пророщенная": {
            "calories": 198,
            "protein": 7.5,
            "fat": 1.3,
            "carbs": 41.4,
            "category": "carbs",
        },
        "пшеничная крупа": {
            "calories": 316,
            "protein": 11.5,
            "fat": 1.3,
            "carbs": 62.0,
            "category": "carbs",
        },
        "пшеничные отруби": {
            "calories": 180,
            "protein": 14.7,
            "fat": 4.1,
            "carbs": 20.6,
            "category": "carbs",
        },
        "пшеничные хлопья": {
            "calories": 336,
            "protein": 16.0,
            "fat": 1.0,
            "carbs": 70.0,
            "category": "carbs",
        },
        "пшенная каша вязкая": {
            "calories": 90,
            "protein": 3.0,
            "fat": 0.7,
            "carbs": 17.0,
            "category": "carbs",
        },
        "пшенная каша рассыпчатая": {
            "calories": 135,
            "protein": 4.7,
            "fat": 1.1,
            "carbs": 26.1,
            "category": "carbs",
        },
        "пшенная крупа": {
            "calories": 348,
            "protein": 11.5,
            "fat": 3.3,
            "carbs": 69.3,
            "category": "carbs",
        },
        "пшенные хлопья": {
            "calories": 334,
            "protein": 12.0,
            "fat": 2.9,
            "carbs": 69.3,
            "category": "carbs",
        },
        "рис арборио": {
            "calories": 330,
            "protein": 6.5,
            "fat": 0.7,
            "carbs": 75.4,
            "category": "carbs",
        },
        "рис басмати": {
            "calories": 322,
            "protein": 7.1,
            "fat": 0.2,
            "carbs": 71.2,
            "category": "carbs",
        },
        "рис белый вареный": {
            "calories": 116,
            "protein": 2.2,
            "fat": 0.5,
            "carbs": 24.9,
            "category": "carbs",
        },
        "рис белый сухой": {
            "calories": 344,
            "protein": 6.7,
            "fat": 0.7,
            "carbs": 78.9,
            "category": "carbs",
        },
        "рис бурый вареный": {
            "calories": 110,
            "protein": 2.6,
            "fat": 0.9,
            "carbs": 22.8,
            "category": "carbs",
        },
        "рис бурый сухой": {
            "calories": 337,
            "protein": 7.4,
            "fat": 1.8,
            "carbs": 72.9,
            "category": "carbs",
        },
        "рис дикий вареный": {
            "calories": 100,
            "protein": 4.0,
            "fat": 0.3,
            "carbs": 21.1,
            "category": "carbs",
        },
        "рис дикий": {
            "calories": 357,
            "protein": 14.0,
            "fat": 0.5,
            "carbs": 72.0,
            "category": "carbs",
        },
        "рис длиннозерный": {
            "calories": 365,
            "protein": 7.1,
            "fat": 0.7,
            "carbs": 78.0,
            "category": "carbs",
        },
        "рис для суши": {
            "calories": 342,
            "protein": 7.0,
            "fat": 0.6,
            "carbs": 75.2,
            "category": "carbs",
        },
        "рис жасмин": {
            "calories": 331,
            "protein": 6.9,
            "fat": 0.2,
            "carbs": 73.4,
            "category": "carbs",
        },
        "рис золотистый": {
            "calories": 349,
            "protein": 8.1,
            "fat": 0.4,
            "carbs": 78.0,
            "category": "carbs",
        },
        "рис карнароли": {
            "calories": 303,
            "protein": 7.5,
            "fat": 2.6,
            "carbs": 62.5,
            "category": "carbs",
        },
        "рис коричневый вареный": {
            "calories": 110,
            "protein": 2.6,
            "fat": 0.9,
            "carbs": 22.8,
            "category": "carbs",
        },
        "рис коричневый": {
            "calories": 331,
            "protein": 6.3,
            "fat": 4.4,
            "carbs": 65.1,
            "category": "carbs",
        },
        "рис красный": {
            "calories": 362,
            "protein": 10.5,
            "fat": 2.5,
            "carbs": 70.5,
            "category": "carbs",
        },
        "рис круглозерный": {
            "calories": 350,
            "protein": 0.1,
            "fat": 0.4,
            "carbs": 79.0,
            "category": "carbs",
        },
        "рис нешлифованный вареный": {
            "calories": 125,
            "protein": 2.7,
            "fat": 0.7,
            "carbs": 36.0,
            "category": "carbs",
        },
        "рис пропаренный вареный": {
            "calories": 97,
            "protein": 2.1,
            "fat": 0.1,
            "carbs": 21.4,
            "category": "carbs",
        },
        "рис рассыпчатый": {
            "calories": 113,
            "protein": 2.4,
            "fat": 0.2,
            "carbs": 24.9,
            "category": "carbs",
        },
        "рис ширатаки": {
            "calories": 9,
            "protein": 0.0,
            "fat": 0.0,
            "carbs": 0.6,
            "category": "carbs",
        },
        "рисовая каша на воде": {
            "calories": 78,
            "protein": 1.5,
            "fat": 0.1,
            "carbs": 17.4,
            "category": "carbs",
        },
        "рисовая каша на молоке": {
            "calories": 97,
            "protein": 2.5,
            "fat": 3.1,
            "carbs": 16.0,
            "category": "carbs",
        },
        "рисовая манка": {
            "calories": 340,
            "protein": 7.0,
            "fat": 0.5,
            "carbs": 78.0,
            "category": "carbs",
        },
        "рисовые отруби": {
            "calories": 316,
            "protein": 13.4,
            "fat": 20.9,
            "carbs": 28.9,
            "category": "carbs",
        },
        "рисовые хлопья": {
            "calories": 360,
            "protein": 7.0,
            "fat": 2.0,
            "carbs": 77.0,
            "category": "carbs",
        },
        "рожь зерна": {
            "calories": 283,
            "protein": 9.9,
            "fat": 2.2,
            "carbs": 55.8,
            "category": "carbs",
        },
        "ржаные отруби": {
            "calories": 221,
            "protein": 11.2,
            "fat": 3.2,
            "carbs": 32.0,
            "category": "carbs",
        },
        "ржаные хлопья": {
            "calories": 343,
            "protein": 6.4,
            "fat": 3.2,
            "carbs": 82.6,
            "category": "carbs",
        },
        "саго": {
            "calories": 350,
            "protein": 1.0,
            "fat": 0.7,
            "carbs": 85.0,
            "category": "carbs",
        },
        "сорго": {
            "calories": 323,
            "protein": 11.8,
            "fat": 3.3,
            "carbs": 66.4,
            "category": "carbs",
        },
        "теф": {
            "calories": 367,
            "protein": 13.3,
            "fat": 2.4,
            "carbs": 73.1,
            "category": "carbs",
        },
        "толокно": {
            "calories": 363,
            "protein": 12.5,
            "fat": 6.0,
            "carbs": 64.9,
            "category": "carbs",
        },
        "толокно гречневое": {
            "calories": 308,
            "protein": 12.6,
            "fat": 3.3,
            "carbs": 57.1,
            "category": "carbs",
        },
        "толокно кукурузное": {
            "calories": 328,
            "protein": 8.3,
            "fat": 1.2,
            "carbs": 71.0,
            "category": "carbs",
        },
        "толокно овсяное": {
            "calories": 306,
            "protein": 11.5,
            "fat": 6.0,
            "carbs": 52.1,
            "category": "carbs",
        },
        "тритикале": {
            "calories": 274,
            "protein": 12.8,
            "fat": 2.1,
            "carbs": 54.5,
            "category": "carbs",
        },
        "фасоль белая": {
            "calories": 350,
            "protein": 21.0,
            "fat": 2.0,
            "carbs": 62.0,
            "category": "carbs",
        },
        "фасоль красная": {
            "calories": 350,
            "protein": 21.0,
            "fat": 2.0,
            "carbs": 62.0,
            "category": "carbs",
        },
        "фасоль кидни": {
            "calories": 290,
            "protein": 21.0,
            "fat": 2.0,
            "carbs": 47.0,
            "category": "carbs",
        },
        "хлопья 4 злака": {
            "calories": 320,
            "protein": 11.4,
            "fat": 2.8,
            "carbs": 51.1,
            "category": "carbs",
        },
        "хлопья 5 злаков": {
            "calories": 370,
            "protein": 11.0,
            "fat": 3.0,
            "carbs": 75.0,
            "category": "carbs",
        },
        "хлопья 7 злаков": {
            "calories": 320,
            "protein": 12.0,
            "fat": 5.0,
            "carbs": 56.0,
            "category": "carbs",
        },
        "чечевица зелёная": {
            "calories": 328,
            "protein": 19.4,
            "fat": 1.1,
            "carbs": 66.6,
            "category": "carbs",
        },
        "чечевица красная": {
            "calories": 322,
            "protein": 25.0,
            "fat": 1.1,
            "carbs": 53.0,
            "category": "carbs",
        },
        "чечевица жёлтая": {
            "calories": 332,
            "protein": 22.3,
            "fat": 0.1,
            "carbs": 65.5,
            "category": "carbs",
        },
        "ячменная каша": {
            "calories": 310,
            "protein": 11.5,
            "fat": 2.0,
            "carbs": 65.8,
            "category": "carbs",
        },
        "ячменная крупа": {
            "calories": 324,
            "protein": 10.0,
            "fat": 1.3,
            "carbs": 71.7,
            "category": "carbs",
        },
        "ячменные хлопья": {
            "calories": 355,
            "protein": 9.8,
            "fat": 3.6,
            "carbs": 79.4,
            "category": "carbs",
        },
        "ячневая каша на воде": {
            "calories": 76,
            "protein": 2.3,
            "fat": 0.3,
            "carbs": 15.7,
            "category": "carbs",
        },
        "ячневая каша на молоке": {
            "calories": 111,
            "protein": 3.6,
            "fat": 2.0,
            "carbs": 19.8,
            "category": "carbs",
        },
        "ячневая крупа": {
            "calories": 324,
            "protein": 10.4,
            "fat": 1.3,
            "carbs": 66.3,
            "category": "carbs",
        },
        "ячка": {
            "calories": 324,
            "protein": 10.4,
            "fat": 1.3,
            "carbs": 66.3,
            "category": "carbs",
        },
        # Хлеб и выпечка
        "хлеб белый": {
            "calories": 265,
            "protein": 8.1,
            "fat": 3.2,
            "carbs": 48.8,
            "category": "carbs",
        },
        "хлеб": {
            "calories": 213,
            "protein": 7.5,
            "fat": 1.8,
            "carbs": 42.0,
            "category": "carbs",
        },
        "хлеб ржаной": {
            "calories": 174,
            "protein": 6.6,
            "fat": 1.2,
            "carbs": 33.4,
            "category": "carbs",
        },
        "хлеб цельнозерновой": {
            "calories": 213,
            "protein": 7.5,
            "fat": 1.8,
            "carbs": 42.0,
            "category": "carbs",
        },
        "батон": {
            "calories": 260,
            "protein": 7.7,
            "fat": 2.9,
            "carbs": 50.9,
            "category": "carbs",
        },
        "лаваш": {
            "calories": 275,
            "protein": 7.9,
            "fat": 1.0,
            "carbs": 57.1,
            "category": "carbs",
        },
        "тосты": {
            "calories": 330,
            "protein": 11.0,
            "fat": 3.5,
            "carbs": 62.0,
            "category": "carbs",
        },
        "булка": {
            "calories": 260,
            "protein": 7.7,
            "fat": 2.9,
            "carbs": 50.9,
            "category": "carbs",
        },
        # Бобовые (вареные)
        "фасоль": {
            "calories": 123,
            "protein": 8.4,
            "fat": 0.5,
            "carbs": 21.5,
            "category": "carbs",
        },
        "чечевица": {
            "calories": 111,
            "protein": 7.8,
            "fat": 0.4,
            "carbs": 19.5,
            "category": "carbs",
        },
        "нут": {
            "calories": 127,
            "protein": 7.2,
            "fat": 2.0,
            "carbs": 19.0,
            "category": "carbs",
        },
        "горох": {
            "calories": 116,
            "protein": 8.0,
            "fat": 0.4,
            "carbs": 20.5,
            "category": "carbs",
        },
        "соя": {
            "calories": 141,
            "protein": 12.4,
            "fat": 6.4,
            "carbs": 9.9,
            "category": "carbs",
        },
        # Картофель
        "картофель вареный": {
            "calories": 82,
            "protein": 2.0,
            "fat": 0.4,
            "carbs": 16.7,
            "category": "carbs",
        },
        "картофель": {
            "calories": 77,
            "protein": 2.0,
            "fat": 0.4,
            "carbs": 16.3,
            "category": "vegetables",
        },
        "картофель жареный": {
            "calories": 192,
            "protein": 2.8,
            "fat": 9.5,
            "carbs": 23.4,
            "category": "carbs",
        },
        "картофельное пюре": {
            "calories": 106,
            "protein": 2.1,
            "fat": 4.2,
            "carbs": 14.3,
            "category": "carbs",
        },
        # ==== ОВОЩИ ====
        "огурцы": {
            "calories": 15,
            "protein": 0.8,
            "fat": 0.1,
            "carbs": 2.8,
            "category": "vegetables",
        },
        "огурец": {
            "calories": 15,
            "protein": 0.8,
            "fat": 0.1,
            "carbs": 2.8,
            "category": "vegetables",
        },
        "помидоры": {
            "calories": 20,
            "protein": 0.6,
            "fat": 0.2,
            "carbs": 4.2,
            "category": "vegetables",
        },
        "помидор": {
            "calories": 20,
            "protein": 0.6,
            "fat": 0.2,
            "carbs": 4.2,
            "category": "vegetables",
        },
        "помидоры черри": {
            "calories": 18,
            "protein": 0.9,
            "fat": 0.2,
            "carbs": 2.8,
            "category": "vegetables",
        },
        "перец болгарский": {
            "calories": 27,
            "protein": 1.3,
            "fat": 0.0,
            "carbs": 5.3,
            "category": "vegetables",
        },
        "перец": {
            "calories": 27,
            "protein": 1.3,
            "fat": 0.0,
            "carbs": 5.3,
            "category": "vegetables",
        },
        "перец красный": {
            "calories": 27,
            "protein": 1.3,
            "fat": 0.0,
            "carbs": 5.3,
            "category": "vegetables",
        },
        "перец желтый": {
            "calories": 27,
            "protein": 1.3,
            "fat": 0.0,
            "carbs": 5.3,
            "category": "vegetables",
        },
        "перец зеленый": {
            "calories": 20,
            "protein": 1.3,
            "fat": 0.0,
            "carbs": 4.6,
            "category": "vegetables",
        },
        "капуста белокочанная": {
            "calories": 27,
            "protein": 1.8,
            "fat": 0.1,
            "carbs": 4.7,
            "category": "vegetables",
        },
        "капуста": {
            "calories": 27,
            "protein": 1.8,
            "fat": 0.1,
            "carbs": 4.7,
            "category": "vegetables",
        },
        "капуста цветная": {
            "calories": 30,
            "protein": 2.5,
            "fat": 0.3,
            "carbs": 4.2,
            "category": "vegetables",
        },
        "капуста пекинская": {
            "calories": 16,
            "protein": 1.2,
            "fat": 0.2,
            "carbs": 2.0,
            "category": "vegetables",
        },
        "капуста брюссельская": {
            "calories": 43,
            "protein": 3.4,
            "fat": 0.3,
            "carbs": 5.9,
            "category": "vegetables",
        },
        "брокколи": {
            "calories": 34,
            "protein": 2.8,
            "fat": 0.4,
            "carbs": 5.2,
            "category": "vegetables",
        },
        "морковь": {
            "calories": 35,
            "protein": 1.3,
            "fat": 0.1,
            "carbs": 6.9,
            "category": "vegetables",
        },
        "свекла": {
            "calories": 43,
            "protein": 1.5,
            "fat": 0.1,
            "carbs": 8.8,
            "category": "vegetables",
        },
        "кабачок": {
            "calories": 24,
            "protein": 0.6,
            "fat": 0.3,
            "carbs": 4.6,
            "category": "vegetables",
        },
        "цуккини": {
            "calories": 17,
            "protein": 1.2,
            "fat": 0.3,
            "carbs": 3.1,
            "category": "vegetables",
        },
        "баклажан": {
            "calories": 24,
            "protein": 1.2,
            "fat": 0.1,
            "carbs": 4.5,
            "category": "vegetables",
        },
        "тыква": {
            "calories": 22,
            "protein": 1.0,
            "fat": 0.1,
            "carbs": 4.4,
            "category": "vegetables",
        },
        "редис": {
            "calories": 16,
            "protein": 1.2,
            "fat": 0.1,
            "carbs": 1.9,
            "category": "vegetables",
        },
        "лук репчатый": {
            "calories": 41,
            "protein": 1.4,
            "fat": 0.0,
            "carbs": 8.2,
            "category": "vegetables",
        },
        "лук": {
            "calories": 41,
            "protein": 1.4,
            "fat": 0.0,
            "carbs": 8.2,
            "category": "vegetables",
        },
        "лук зеленый": {
            "calories": 20,
            "protein": 1.3,
            "fat": 0.0,
            "carbs": 3.5,
            "category": "vegetables",
        },
        "чеснок": {
            "calories": 143,
            "protein": 6.5,
            "fat": 0.5,
            "carbs": 29.9,
            "category": "vegetables",
        },
        "имбирь": {
            "calories": 80,
            "protein": 1.8,
            "fat": 0.8,
            "carbs": 15.8,
            "category": "vegetables",
        },
        # Зелень
        "листья салата": {
            "calories": 12,
            "protein": 1.2,
            "fat": 0.2,
            "carbs": 1.3,
            "category": "vegetables",
        },
        "салат": {
            "calories": 12,
            "protein": 1.2,
            "fat": 0.2,
            "carbs": 1.3,
            "category": "vegetables",
        },
        "шпинат": {
            "calories": 22,
            "protein": 2.9,
            "fat": 0.3,
            "carbs": 2.0,
            "category": "vegetables",
        },
        "руккола": {
            "calories": 25,
            "protein": 2.6,
            "fat": 0.7,
            "carbs": 2.1,
            "category": "vegetables",
        },
        "укроп": {
            "calories": 38,
            "protein": 2.5,
            "fat": 0.5,
            "carbs": 6.3,
            "category": "vegetables",
        },
        "петрушка": {
            "calories": 36,
            "protein": 3.0,
            "fat": 0.4,
            "carbs": 7.6,
            "category": "vegetables",
        },
        "базилик": {
            "calories": 27,
            "protein": 3.1,
            "fat": 0.6,
            "carbs": 4.3,
            "category": "vegetables",
        },
        "кинза": {
            "calories": 23,
            "protein": 2.1,
            "fat": 0.5,
            "carbs": 3.7,
            "category": "vegetables",
        },
        "зелень": {
            "calories": 18,
            "protein": 1.8,
            "fat": 0.3,
            "carbs": 2.2,
            "category": "vegetables",
        },
        "листовая зелень": {
            "calories": 18,
            "protein": 1.8,
            "fat": 0.3,
            "carbs": 2.2,
            "category": "vegetables",
        },
        # Грибы
        "грибы шампиньоны": {
            "calories": 27,
            "protein": 4.3,
            "fat": 1.0,
            "carbs": 0.1,
            "category": "vegetables",
        },
        "грибы": {
            "calories": 27,
            "protein": 4.3,
            "fat": 1.0,
            "carbs": 0.1,
            "category": "vegetables",
        },
        "грибы белые": {
            "calories": 34,
            "protein": 3.7,
            "fat": 1.7,
            "carbs": 1.1,
            "category": "vegetables",
        },
        "грибы лисички": {
            "calories": 19,
            "protein": 1.5,
            "fat": 1.0,
            "carbs": 2.2,
            "category": "vegetables",
        },
        "грибы вешенки": {
            "calories": 38,
            "protein": 2.5,
            "fat": 0.5,
            "carbs": 6.5,
            "category": "vegetables",
        },
        # Расширенная база грибов с calorizator.ru
        "белые грибы": {
            "calories": 34.0,
            "protein": 3.7,
            "fat": 1.7,
            "carbs": 1.1,
            "category": "mushrooms",
        },
        "белые жареные": {
            "calories": 162.0,
            "protein": 4.6,
            "fat": 11.5,
            "carbs": 10.7,
            "category": "mushrooms",
        },
        "белые маринованные": {
            "calories": 24.0,
            "protein": 3.0,
            "fat": 0.5,
            "carbs": 2.0,
            "category": "mushrooms",
        },
        "белые свежие": {
            "calories": 34.0,
            "protein": 3.7,
            "fat": 1.7,
            "carbs": 1.1,
            "category": "mushrooms",
        },
        "белые сушёные": {
            "calories": 286.0,
            "protein": 30.3,
            "fat": 14.3,
            "carbs": 9.0,
            "category": "mushrooms",
        },
        "вешенки маринованные": {
            "calories": 23.0,
            "protein": 1.0,
            "fat": 1.5,
            "carbs": 0.0,
            "category": "mushrooms",
        },
        "вешенки свежие": {
            "calories": 38.0,
            "protein": 2.5,
            "fat": 0.3,
            "carbs": 6.5,
            "category": "mushrooms",
        },
        "вешенки": {
            "calories": 38.0,
            "protein": 2.5,
            "fat": 0.3,
            "carbs": 6.5,
            "category": "mushrooms",
        },
        "грузди маринованные": {
            "calories": 26.0,
            "protein": 1.0,
            "fat": 1.8,
            "carbs": 0.0,
            "category": "mushrooms",
        },
        "грузди свежие": {
            "calories": 16.0,
            "protein": 1.8,
            "fat": 0.5,
            "carbs": 0.8,
            "category": "mushrooms",
        },
        "грузди": {
            "calories": 16.0,
            "protein": 1.8,
            "fat": 0.5,
            "carbs": 0.8,
            "category": "mushrooms",
        },
        "дождевики": {
            "calories": 27.0,
            "protein": 4.3,
            "fat": 1.0,
            "carbs": 1.0,
            "category": "mushrooms",
        },
        "еноки": {
            "calories": 42.0,
            "protein": 2.7,
            "fat": 0.4,
            "carbs": 0.2,
            "category": "mushrooms",
        },
        "лисички свежие": {
            "calories": 19.0,
            "protein": 1.5,
            "fat": 1.0,
            "carbs": 1.0,
            "category": "mushrooms",
        },
        "лисички": {
            "calories": 19.0,
            "protein": 1.5,
            "fat": 1.0,
            "carbs": 1.0,
            "category": "mushrooms",
        },
        "лисички сушёные": {
            "calories": 261.0,
            "protein": 22.3,
            "fat": 7.6,
            "carbs": 24.2,
            "category": "mushrooms",
        },
        "маслята маринованные": {
            "calories": 18.0,
            "protein": 3.0,
            "fat": 0.5,
            "carbs": 1.4,
            "category": "mushrooms",
        },
        "маслята свежие": {
            "calories": 19.0,
            "protein": 2.4,
            "fat": 0.7,
            "carbs": 1.7,
            "category": "mushrooms",
        },
        "маслята": {
            "calories": 19.0,
            "protein": 2.4,
            "fat": 0.7,
            "carbs": 1.7,
            "category": "mushrooms",
        },
        "опята маринованные": {
            "calories": 18.0,
            "protein": 1.8,
            "fat": 1.0,
            "carbs": 0.4,
            "category": "mushrooms",
        },
        "опята свежие": {
            "calories": 22.0,
            "protein": 2.2,
            "fat": 1.2,
            "carbs": 0.5,
            "category": "mushrooms",
        },
        "опята": {
            "calories": 22.0,
            "protein": 2.2,
            "fat": 1.2,
            "carbs": 0.5,
            "category": "mushrooms",
        },
        "подберёзовики свежие": {
            "calories": 20.0,
            "protein": 2.1,
            "fat": 0.8,
            "carbs": 1.2,
            "category": "mushrooms",
        },
        "подберёзовики": {
            "calories": 20.0,
            "protein": 2.1,
            "fat": 0.8,
            "carbs": 1.2,
            "category": "mushrooms",
        },
        "подберёзовики сушёные": {
            "calories": 231.0,
            "protein": 23.5,
            "fat": 9.2,
            "carbs": 14.3,
            "category": "mushrooms",
        },
        "подосиновики свежие": {
            "calories": 22.0,
            "protein": 3.3,
            "fat": 0.5,
            "carbs": 1.2,
            "category": "mushrooms",
        },
        "подосиновики": {
            "calories": 22.0,
            "protein": 3.3,
            "fat": 0.5,
            "carbs": 1.2,
            "category": "mushrooms",
        },
        "подосиновики сушёные": {
            "calories": 315.0,
            "protein": 35.4,
            "fat": 5.4,
            "carbs": 33.2,
            "category": "mushrooms",
        },
        "польский гриб": {
            "calories": 19.0,
            "protein": 1.7,
            "fat": 0.7,
            "carbs": 1.5,
            "category": "mushrooms",
        },
        "портобелло жареные": {
            "calories": 35.0,
            "protein": 4.3,
            "fat": 0.8,
            "carbs": 2.7,
            "category": "mushrooms",
        },
        "портобелло свежие": {
            "calories": 26.0,
            "protein": 2.5,
            "fat": 0.2,
            "carbs": 3.6,
            "category": "mushrooms",
        },
        "портобелло": {
            "calories": 26.0,
            "protein": 2.5,
            "fat": 0.2,
            "carbs": 3.6,
            "category": "mushrooms",
        },
        "рыжики свежие": {
            "calories": 17.0,
            "protein": 1.9,
            "fat": 0.8,
            "carbs": 2.7,
            "category": "mushrooms",
        },
        "рыжики": {
            "calories": 17.0,
            "protein": 1.9,
            "fat": 0.8,
            "carbs": 2.7,
            "category": "mushrooms",
        },
        "сморчки свежие": {
            "calories": 27.0,
            "protein": 1.7,
            "fat": 0.3,
            "carbs": 4.2,
            "category": "mushrooms",
        },
        "сморчки": {
            "calories": 27.0,
            "protein": 1.7,
            "fat": 0.3,
            "carbs": 4.2,
            "category": "mushrooms",
        },
        "сыроежки свежие": {
            "calories": 19.0,
            "protein": 1.7,
            "fat": 0.7,
            "carbs": 1.5,
            "category": "mushrooms",
        },
        "сыроежки": {
            "calories": 19.0,
            "protein": 1.7,
            "fat": 0.7,
            "carbs": 1.5,
            "category": "mushrooms",
        },
        "трюфели свежие": {
            "calories": 51.0,
            "protein": 5.9,
            "fat": 0.5,
            "carbs": 5.3,
            "category": "mushrooms",
        },
        "трюфели": {
            "calories": 51.0,
            "protein": 5.9,
            "fat": 0.5,
            "carbs": 5.3,
            "category": "mushrooms",
        },
        "чернушки": {
            "calories": 9.0,
            "protein": 1.5,
            "fat": 0.3,
            "carbs": 0.1,
            "category": "mushrooms",
        },
        "шампиньоны": {
            "calories": 27.0,
            "protein": 4.3,
            "fat": 1.0,
            "carbs": 0.1,
            "category": "mushrooms",
        },
        "шампиньоны свежие": {
            "calories": 27.0,
            "protein": 4.3,
            "fat": 1.0,
            "carbs": 0.1,
            "category": "mushrooms",
        },
        "шампиньоны сушеные": {
            "calories": 261.0,
            "protein": 26.8,
            "fat": 4.5,
            "carbs": 30.0,
            "category": "mushrooms",
        },
        "шиитаке свежие": {
            "calories": 34.0,
            "protein": 2.2,
            "fat": 0.5,
            "carbs": 6.8,
            "category": "mushrooms",
        },
        "шиитаке": {
            "calories": 34.0,
            "protein": 2.2,
            "fat": 0.5,
            "carbs": 6.8,
            "category": "mushrooms",
        },
        "шиитаке сушеные": {
            "calories": 331.0,
            "protein": 19.3,
            "fat": 0.0,
            "carbs": 63.4,
            "category": "mushrooms",
        },
        "эринги": {
            "calories": 43.0,
            "protein": 3.3,
            "fat": 0.4,
            "carbs": 4.2,
            "category": "mushrooms",
        },
        # ==== ФРУКТЫ И ЯГОДЫ ====
        "яблоко": {
            "calories": 52,
            "protein": 0.4,
            "fat": 0.4,
            "carbs": 11.8,
            "category": "fruits",
        },
        "яблоки": {
            "calories": 52,
            "protein": 0.4,
            "fat": 0.4,
            "carbs": 11.8,
            "category": "fruits",
        },
        "груша": {
            "calories": 42,
            "protein": 0.4,
            "fat": 0.3,
            "carbs": 10.3,
            "category": "fruits",
        },
        "банан": {
            "calories": 96,
            "protein": 1.5,
            "fat": 0.2,
            "carbs": 21.0,
            "category": "fruits",
        },
        "апельсин": {
            "calories": 43,
            "protein": 0.9,
            "fat": 0.2,
            "carbs": 8.1,
            "category": "fruits",
        },
        "мандарин": {
            "calories": 38,
            "protein": 0.8,
            "fat": 0.2,
            "carbs": 7.5,
            "category": "fruits",
        },
        "грейпфрут": {
            "calories": 35,
            "protein": 0.7,
            "fat": 0.2,
            "carbs": 6.5,
            "category": "fruits",
        },
        "лимон": {
            "calories": 16,
            "protein": 0.9,
            "fat": 0.1,
            "carbs": 3.0,
            "category": "fruits",
        },
        "киви": {
            "calories": 61,
            "protein": 1.1,
            "fat": 0.5,
            "carbs": 10.3,
            "category": "fruits",
        },
        "ананас": {
            "calories": 52,
            "protein": 0.4,
            "fat": 0.1,
            "carbs": 11.8,
            "category": "fruits",
        },
        "манго": {
            "calories": 67,
            "protein": 0.5,
            "fat": 0.3,
            "carbs": 14.8,
            "category": "fruits",
        },
        "персик": {
            "calories": 45,
            "protein": 0.9,
            "fat": 0.1,
            "carbs": 9.5,
            "category": "fruits",
        },
        "абрикос": {
            "calories": 44,
            "protein": 0.9,
            "fat": 0.1,
            "carbs": 9.0,
            "category": "fruits",
        },
        "слива": {
            "calories": 42,
            "protein": 0.8,
            "fat": 0.3,
            "carbs": 9.6,
            "category": "fruits",
        },
        "арбуз": {
            "calories": 30,
            "protein": 0.6,
            "fat": 0.1,
            "carbs": 5.8,
            "category": "fruits",
        },
        "дыня": {
            "calories": 34,
            "protein": 0.6,
            "fat": 0.3,
            "carbs": 7.4,
            "category": "fruits",
        },
        "вишня": {
            "calories": 52,
            "protein": 0.8,
            "fat": 0.2,
            "carbs": 10.6,
            "category": "fruits",
        },
        "черешня": {
            "calories": 52,
            "protein": 1.1,
            "fat": 0.4,
            "carbs": 10.6,
            "category": "fruits",
        },
        # Ягоды
        "клубника": {
            "calories": 32,
            "protein": 0.8,
            "fat": 0.4,
            "carbs": 5.7,
            "category": "fruits",
        },
        "малина": {
            "calories": 46,
            "protein": 0.8,
            "fat": 0.5,
            "carbs": 8.3,
            "category": "fruits",
        },
        "черника": {
            "calories": 44,
            "protein": 1.1,
            "fat": 0.6,
            "carbs": 7.6,
            "category": "fruits",
        },
        "голубика": {
            "calories": 39,
            "protein": 1.0,
            "fat": 0.5,
            "carbs": 6.6,
            "category": "fruits",
        },
        "смородина черная": {
            "calories": 44,
            "protein": 1.0,
            "fat": 0.2,
            "carbs": 7.3,
            "category": "fruits",
        },
        "смородина красная": {
            "calories": 43,
            "protein": 0.6,
            "fat": 0.2,
            "carbs": 7.7,
            "category": "fruits",
        },
        "крыжовник": {
            "calories": 45,
            "protein": 0.7,
            "fat": 0.2,
            "carbs": 9.1,
            "category": "fruits",
        },
        "виноград": {
            "calories": 65,
            "protein": 0.6,
            "fat": 0.2,
            "carbs": 15.4,
            "category": "fruits",
        },
        "ежевика": {
            "calories": 34,
            "protein": 1.5,
            "fat": 0.5,
            "carbs": 4.4,
            "category": "fruits",
        },
        # Сухофрукты
        "изюм": {
            "calories": 264,
            "protein": 2.9,
            "fat": 0.6,
            "carbs": 66.0,
            "category": "fruits",
        },
        "чернослив": {
            "calories": 231,
            "protein": 2.3,
            "fat": 0.7,
            "carbs": 57.5,
            "category": "fruits",
        },
        "курага": {
            "calories": 215,
            "protein": 5.2,
            "fat": 0.3,
            "carbs": 51.0,
            "category": "fruits",
        },
        "финики": {
            "calories": 274,
            "protein": 2.5,
            "fat": 0.5,
            "carbs": 69.2,
            "category": "fruits",
        },
        "инжир сушеный": {
            "calories": 257,
            "protein": 3.1,
            "fat": 0.8,
            "carbs": 57.9,
            "category": "fruits",
        },
        # ==== ОРЕХИ И СЕМЕНА ====
        "миндаль": {
            "calories": 609,
            "protein": 18.6,
            "fat": 53.7,
            "carbs": 13.0,
            "category": "nuts",
        },
        "грецкие орехи": {
            "calories": 656,
            "protein": 16.2,
            "fat": 60.8,
            "carbs": 11.1,
            "category": "nuts",
        },
        "грецкий орех": {
            "calories": 656,
            "protein": 16.2,
            "fat": 60.8,
            "carbs": 11.1,
            "category": "nuts",
        },
        "орехи": {
            "calories": 628,
            "protein": 17.0,
            "fat": 57.0,
            "carbs": 12.0,
            "category": "nuts",
        },
        "кешью": {
            "calories": 553,
            "protein": 18.5,
            "fat": 48.5,
            "carbs": 22.5,
            "category": "nuts",
        },
        "фундук": {
            "calories": 651,
            "protein": 15.0,
            "fat": 61.5,
            "carbs": 9.4,
            "category": "nuts",
        },
        "арахис": {
            "calories": 567,
            "protein": 26.3,
            "fat": 45.2,
            "carbs": 9.9,
            "category": "nuts",
        },
        "фисташки": {
            "calories": 562,
            "protein": 20.0,
            "fat": 45.0,
            "carbs": 27.0,
            "category": "nuts",
        },
        "кедровые орехи": {
            "calories": 673,
            "protein": 13.7,
            "fat": 68.4,
            "carbs": 9.4,
            "category": "nuts",
        },
        "семена подсолнечника": {
            "calories": 601,
            "protein": 20.7,
            "fat": 52.9,
            "carbs": 10.5,
            "category": "nuts",
        },
        "семечки": {
            "calories": 601,
            "protein": 20.7,
            "fat": 52.9,
            "carbs": 10.5,
            "category": "nuts",
        },
        "семена тыквы": {
            "calories": 541,
            "protein": 24.5,
            "fat": 45.8,
            "carbs": 4.7,
            "category": "nuts",
        },
        "семена льна": {
            "calories": 534,
            "protein": 18.3,
            "fat": 42.2,
            "carbs": 28.9,
            "category": "nuts",
        },
        "семена чиа": {
            "calories": 486,
            "protein": 16.5,
            "fat": 30.7,
            "carbs": 42.1,
            "category": "nuts",
        },
        "кунжут": {
            "calories": 565,
            "protein": 19.4,
            "fat": 48.7,
            "carbs": 12.2,
            "category": "nuts",
        },
        # ==== МАСЛА И ЖИРЫ ====
        "масло оливковое": {
            "calories": 898,
            "protein": 0.0,
            "fat": 99.8,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло подсолнечное": {
            "calories": 900,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло льняное": {
            "calories": 898,
            "protein": 0.0,
            "fat": 99.8,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло кокосовое": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло сливочное": {
            "calories": 748,
            "protein": 0.5,
            "fat": 82.5,
            "carbs": 0.8,
            "category": "fats",
        },
        "авокадо": {
            "calories": 160,
            "protein": 2.0,
            "fat": 14.7,
            "carbs": 1.8,
            "category": "fats",
        },
        "майонез": {
            "calories": 627,
            "protein": 3.1,
            "fat": 67.0,
            "carbs": 2.6,
            "category": "fats",
        },
        # Расширенная база масел и жиров с calorizator.ru
        "жир бараний": {
            "calories": 897,
            "protein": 0.0,
            "fat": 99.7,
            "carbs": 0.0,
            "category": "fats",
        },
        "жир говяжий": {
            "calories": 897,
            "protein": 0.0,
            "fat": 99.7,
            "carbs": 0.0,
            "category": "fats",
        },
        "жир из печени трески": {
            "calories": 898,
            "protein": 0.0,
            "fat": 99.8,
            "carbs": 0.0,
            "category": "fats",
        },
        "жир кулинарный": {
            "calories": 897,
            "protein": 0.0,
            "fat": 99.7,
            "carbs": 0.0,
            "category": "fats",
        },
        "жир куриный": {
            "calories": 897,
            "protein": 0.0,
            "fat": 99.7,
            "carbs": 0.0,
            "category": "fats",
        },
        "жир рыбий": {
            "calories": 902,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "жир свиной": {
            "calories": 896,
            "protein": 0.0,
            "fat": 99.6,
            "carbs": 0.0,
            "category": "fats",
        },
        "маргарин": {
            "calories": 743,
            "protein": 0.3,
            "fat": 82.0,
            "carbs": 1.0,
            "category": "fats",
        },
        "маргарин низкокалорийный": {
            "calories": 545,
            "protein": 0.5,
            "fat": 60.0,
            "carbs": 0.7,
            "category": "fats",
        },
        "маргарин сливочный": {
            "calories": 745,
            "protein": 0.5,
            "fat": 82.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло абрикосовое": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло авокадо": {
            "calories": 884,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло амаранта": {
            "calories": 736,
            "protein": 0.0,
            "fat": 81.8,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло арахисовое": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло виноградных косточек": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло горчичное": {
            "calories": 898,
            "protein": 0.0,
            "fat": 99.8,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло грецкого ореха": {
            "calories": 898,
            "protein": 0.0,
            "fat": 99.8,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло гхи": {
            "calories": 902,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло гхи топленое": {
            "calories": 902,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло зародышей пшеницы": {
            "calories": 884,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло какао": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло канолы": {
            "calories": 898,
            "protein": 0.0,
            "fat": 99.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло кедровое": {
            "calories": 898,
            "protein": 0.0,
            "fat": 99.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло конопляное": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло кукурузное": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло кунжутное": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло макадамии": {
            "calories": 708,
            "protein": 9.2,
            "fat": 74.6,
            "carbs": 10.0,
            "category": "fats",
        },
        "масло маковое": {
            "calories": 898,
            "protein": 0.0,
            "fat": 99.8,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло миндальное": {
            "calories": 816,
            "protein": 0.0,
            "fat": 90.7,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло мускатного ореха": {
            "calories": 899,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.1,
            "category": "fats",
        },
        "масло облепиховое": {
            "calories": 896,
            "protein": 0.0,
            "fat": 99.5,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло овсяное": {
            "calories": 890,
            "protein": 0.0,
            "fat": 99.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло ореховое": {
            "calories": 899,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло пальмовое": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло рапсовое": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло растительное": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло расторопши": {
            "calories": 889,
            "protein": 0.0,
            "fat": 98.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло репейное": {
            "calories": 930,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло рисовое": {
            "calories": 824,
            "protein": 0.0,
            "fat": 91.5,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло рыжиковое": {
            "calories": 900,
            "protein": 0.0,
            "fat": 99.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло сафлоровое": {
            "calories": 880,
            "protein": 0.0,
            "fat": 100.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло сливочное 60%": {
            "calories": 552,
            "protein": 1.3,
            "fat": 60.0,
            "carbs": 1.7,
            "category": "fats",
        },
        "масло сливочное 67%": {
            "calories": 610,
            "protein": 1.0,
            "fat": 67.0,
            "carbs": 1.6,
            "category": "fats",
        },
        "масло сливочное 72.5%": {
            "calories": 662,
            "protein": 1.0,
            "fat": 72.5,
            "carbs": 1.4,
            "category": "fats",
        },
        "масло сливочное 82%": {
            "calories": 740,
            "protein": 0.7,
            "fat": 82.0,
            "carbs": 0.7,
            "category": "fats",
        },
        "масло сливочное 82.5%": {
            "calories": 748,
            "protein": 0.6,
            "fat": 82.5,
            "carbs": 0.8,
            "category": "fats",
        },
        "масло сливочное шоколадное": {
            "calories": 642,
            "protein": 1.5,
            "fat": 62.0,
            "carbs": 18.6,
            "category": "fats",
        },
        "масло соевое": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.9,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло топленое": {
            "calories": 892,
            "protein": 0.2,
            "fat": 99.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло тыквенное": {
            "calories": 896,
            "protein": 0.0,
            "fat": 99.5,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло хлопковое": {
            "calories": 899,
            "protein": 0.0,
            "fat": 99.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "масло ши": {
            "calories": 884,
            "protein": 0.0,
            "fat": 98.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "спред": {
            "calories": 360,
            "protein": 0.0,
            "fat": 40.0,
            "carbs": 0.0,
            "category": "fats",
        },
        "тахина": {
            "calories": 695,
            "protein": 24.0,
            "fat": 62.0,
            "carbs": 10.0,
            "category": "fats",
        },
        "тахини": {
            "calories": 695,
            "protein": 24.0,
            "fat": 62.0,
            "carbs": 10.0,
            "category": "fats",
        },
        # ==== СЛАДОСТИ ====
        "мед": {
            "calories": 329,
            "protein": 0.8,
            "fat": 0.0,
            "carbs": 81.5,
            "category": "sweets",
        },
        "сахар": {
            "calories": 387,
            "protein": 0.0,
            "fat": 0.0,
            "carbs": 99.8,
            "category": "sweets",
        },
        "шоколад темный": {
            "calories": 539,
            "protein": 6.2,
            "fat": 35.4,
            "carbs": 48.2,
            "category": "sweets",
        },
        "шоколад молочный": {
            "calories": 554,
            "protein": 7.7,
            "fat": 31.0,
            "carbs": 60.0,
            "category": "sweets",
        },
        "шоколад": {
            "calories": 554,
            "protein": 7.7,
            "fat": 31.0,
            "carbs": 60.0,
            "category": "sweets",
        },
    }

    # Правила сочетания продуктов для приемов пищи
    MEAL_RULES = {
        "Завтрак": {
            "description": (
                "Должен содержать белки + " "медленные углеводы + немного жиров"
            ),
            "required_categories": ["protein", "carbs"],
            "optional_categories": ["dairy", "fruits", "vegetables", "fats"],
            "avoid": ["много фруктов без белка", "только овощи"],
            "examples": [
                "Яйца + овсянка + овощи",
                "Творог + фрукты + хлеб",
                "Курица + гречка + овощи",
            ],
        },
        "Второй завтрак": {
            "description": "Легкий перекус с белком или фруктами",
            "required_categories": [],
            "optional_categories": ["protein", "dairy", "fruits", "nuts"],
            "avoid": ["тяжелые углеводы"],
            "examples": ["Творог + ягоды", "Орехи + яблоко", "Йогурт"],
        },
        "Обед": {
            "description": "Основной прием: белок + сложные углеводы + овощи",
            "required_categories": ["protein", "carbs", "vegetables"],
            "optional_categories": ["dairy", "fats"],
            "avoid": ["много сахара", "только салат"],
            "examples": [
                "Курица + рис + овощной салат",
                "Говядина + гречка + тушеные овощи",
                "Рыба + макароны + брокколи",
            ],
        },
        "Полдник": {
            "description": "Легкий перекус",
            "required_categories": [],
            "optional_categories": ["protein", "dairy", "fruits", "nuts", "vegetables"],
            "avoid": ["тяжелые блюда"],
            "examples": ["Творог", "Фрукты + орехи", "Овощи + йогурт"],
        },
        "Ужин": {
            "description": "Белок + овощи, минимум углеводов",
            "required_categories": ["protein", "vegetables"],
            "optional_categories": ["dairy", "carbs"],
            "avoid": ["много углеводов", "сладкие фрукты", "тяжелая еда"],
            "examples": [
                "Курица + овощной салат",
                "Рыба + тушеные овощи",
                "Творог + огурцы и зелень",
            ],
        },
        "Поздний ужин": {
            "description": "Легкий белковый перекус",
            "required_categories": ["protein"],
            "optional_categories": ["dairy", "vegetables"],
            "avoid": ["углеводы", "фрукты", "жирное"],
            "examples": ["Творог обезжиренный", "Кефир", "Яйца"],
        },
    }

    def get_product_nutrition(self, product_name: str) -> Optional[Dict]:
        """
        Получить пищевую ценность продукта на 100г с умным поиском

        Args:
            product_name: Название продукта
            use_external_api: Использовать внешние API если не найдено локально

        Returns:
            Dict с КБЖУ или None
        """
        # Нормализуем название
        product_name_lower = product_name.lower().strip()

        # Убираем лишние слова (жареная, вареная, запеченная и т.д.)
        product_name_clean = product_name_lower
        for word in [
            "жареная",
            "жареный",
            "жареное",
            "вареная",
            "вареный",
            "вареное",
            "запеченная",
            "запеченный",
            "запеченное",
            "тушеная",
            "тушеный",
            "тушеное",
            "свежий",
            "свежая",
            "свежее",
            "сырой",
            "сырая",
            "сырое",
        ]:
            product_name_clean = product_name_clean.replace(word, "").strip()

        # Пытаемся найти точное совпадение
        if product_name_clean in self.PRODUCTS:
            return self.PRODUCTS[product_name_clean]

        # Пытаемся найти точное совпадение с исходным названием
        if product_name_lower in self.PRODUCTS:
            return self.PRODUCTS[product_name_lower]

        # Пытаемся найти частичное совпадение
        for key in self.PRODUCTS:
            if product_name_clean in key or key in product_name_clean:
                return self.PRODUCTS[key]

        # Еще одна попытка с ключевыми словами
        keywords = product_name_clean.split()
        for keyword in keywords:
            if len(keyword) > 3:  # Игнорируем короткие слова
                for key in self.PRODUCTS:
                    if keyword in key:
                        return self.PRODUCTS[key]

        return None

    def calculate_nutrition(self, product_name: str, weight_g: float) -> Optional[Dict]:
        """Рассчитать пищевую ценность для указанного веса продукта"""
        base_nutrition = self.get_product_nutrition(product_name)
        if not base_nutrition:
            return None

        multiplier = weight_g / 100.0
        return {
            "calories": round(base_nutrition["calories"] * multiplier, 1),
            "protein": round(base_nutrition["protein"] * multiplier, 1),
            "fat": round(base_nutrition["fat"] * multiplier, 1),
            "carbs": round(base_nutrition["carbs"] * multiplier, 1),
        }

    def get_meal_rules(self, meal_name: str) -> Optional[Dict]:
        """Получить правила для конкретного приема пищи"""
        return self.MEAL_RULES.get(meal_name)

    def find_similar_products(self, product_name: str, limit: int = 5) -> List[str]:
        """Найти похожие продукты в базе"""
        product_name_lower = product_name.lower()
        matches = []

        for key in self.PRODUCTS:
            if product_name_lower in key or key in product_name_lower:
                matches.append(key)

        return matches[:limit]


# Глобальный экземпляр базы данных
nutrition_db = NutritionDatabase()
